DROP TABLE IF EXISTS "Event" CASCADE;
DROP TABLE IF EXISTS "TrackedLink" CASCADE;
DROP TABLE IF EXISTS "CampaignDelivery" CASCADE;
DROP TABLE IF EXISTS "Campaign" CASCADE;
DROP TABLE IF EXISTS "DnsCheck" CASCADE;
DROP TABLE IF EXISTS "Domain" CASCADE;
DROP TABLE IF EXISTS "ContactImportJob" CASCADE;
DROP TABLE IF EXISTS "SuppressionEntry" CASCADE;
DROP TABLE IF EXISTS "ContactTag" CASCADE;
DROP TABLE IF EXISTS "Tag" CASCADE;
DROP TABLE IF EXISTS "Contact" CASCADE;
DROP TABLE IF EXISTS "Segment" CASCADE;

ALTER TABLE "Workspace" DROP COLUMN IF EXISTS "postalAddress";

DROP TYPE IF EXISTS "EventType";
DROP TYPE IF EXISTS "CampaignDeliveryStatus";
DROP TYPE IF EXISTS "CampaignStatus";
DROP TYPE IF EXISTS "DnsCheckType";
DROP TYPE IF EXISTS "DomainStatus";
DROP TYPE IF EXISTS "ContactImportJobStatus";
DROP TYPE IF EXISTS "SuppressionReason";
DROP TYPE IF EXISTS "ContactStatus";
